

insert into country (country_id, country_name, phone_code, country_code) values
        (
            1,
            "Afghanistan",
            "93",
            "AF"
        ),
        (
            2,
            "Albania",
            "355",
            "AL"
        ),
        (
            3,
            "Algeria",
            "213",
            "DZ"
        ),
        (
            4,
            "American Samoa",
            "1-684",
            "AS"
        ),
        (
            5,
            "Andorra",
            "376",
            "AD"
        ),
        (
            6,
            "Angola",
            "244",
            "AO"
        ),
        (
            7,
            "Anguilla",
            "1-264",
            "AI"
        ),
        (
            8,
            "Antarctica",
            "672",
            "AQ"
        ),
        (
            9,
            "Antigua and Barbuda",
            "1-268",
            "AG"
        ),
        (
            10,
            "Argentina",
            "54",
            "AR"
        ),
        (
            11,
            "Armenia",
            "374",
            "AM"
        ),
        (
            12,
            "Aruba",
            "297",
            "AW"
        ),
        (
            13,
            "Australia",
            "61",
            "AU"
        ),
        (
            14,
            "Austria",
            "43",
            "AT"
        ),
        (
            15,
            "Azerbaijan",
            "994",
            "AZ"
        ),
        (
            16,
            "Bahamas",
            "1-242",
            "BS"
        ),
        (
            17,
            "Bahrain",
            "973",
            "BH"
        ),
        (
            18,
            "Bangladesh",
            "880",
            "BD"
        ),
        (
            19,
            "Barbados",
            "1-246",
            "BB"
        ),
        (
            20,
            "Belarus",
            "375",
            "BY"
        ),
        (
            21,
            "Belgium",
            "32",
            "BE"
        ),
        (
            22,
            "Belize",
            "501",
            "BZ"
        ),
        (
            23,
            "Benin",
            "229",
            "BJ"
        ),
        (
            24,
            "Bermuda",
            "1-441",
            "BM"
        ),
        (
            25,
            "Bhutan",
            "975",
            "BT"
        ),
        (
            26,
            "Bolivia",
            "591",
            "BO"
        ),
        (
            27,
            "Bosnia and Herzegovina",
            "387",
            "BA"
        ),
        (
            28,
            "Botswana",
            "267",
            "BW"
        ),
        (
            29,
            "Brazil",
            "55",
            "BR"
        ),
        (
            30,
            "British Indian Ocean Territory",
            "246",
            "IO"
        ),
        (
            31,
            "British Virgin Islands",
            "1-284",
            "VG"
        ),
        (
            32,
            "Brunei",
            "673",
            "BN"
        ),
        (
            33,
            "Bulgaria",
            "359",
            "BG"
        ),
        (
            34,
            "Burkina Faso",
            "226",
            "BF"
        ),
        (
            35,
            "Burundi",
            "257",
            "BI"
        ),
        (
            36,
            "Cambodia",
            "855",
            "KH"
        ),
        (
            37,
            "Cameroon",
            "237",
            "CM"
        ),
        (
            38,
            "Canada",
            "1",
            "CA"
        ),
        (
            39,
            "Cape Verde",
            "238",
            "CV"
        ),
        (
            40,
            "Cayman Islands",
            "1-345",
            "KY"
        ),
        (
            41,
            "Central African Republic",
            "236",
            "CF"
        ),
        (
            42,
            "Chad",
            "235",
            "TD"
        ),
        (
            43,
            "Chile",
            "56",
            "CL"
        ),
        (
            44,
            "China",
            "86",
            "CN"
        ),
        (
            45,
            "Christmas Island",
            "61",
            "CX"
        ),
        (
            46,
            "Cocos Islands",
            "61",
            "CC"
        ),
        (
            47,
            "Colombia",
            "57",
            "CO"
        ),
        (
            48,
            "Comoros",
            "269",
            "KM"
        ),
        (
            49,
            "Cook Islands",
            "682",
            "CK"
        ),
        (
            50,
            "Costa Rica",
            "506",
            "CR"
        ),
        (
            51,
            "Croatia",
            "385",
            "HR"
        ),
        (
            52,
            "Cuba",
            "53",
            "CU"
        ),
        (
            53,
            "Curacao",
            "599",
            "CW"
        ),
        (
            54,
            "Cyprus",
            "357",
            "CY"
        ),
        (
            55,
            "Czech Republic",
            "420",
            "CZ"
        ),
        (
            56,
            "Democratic Republic of the Congo",
            "243",
            "CD"
        ),
        (
            57,
            "Denmark",
            "45",
            "DK"
        ),
        (
            58,
            "Djibouti",
            "253",
            "DJ"
        ),
        (
            59,
            "Dominica",
            "1-767",
            "DM"
        ),
        (
            60,
            "Dominican Republic",
            "1-809",
            "DO"
        ),
        (
            61,
            "East Timor",
            "670",
            "TL"
        ),
        (
            62,
            "Ecuador",
            "593",
            "EC"
        ),
        (
            63,
            "Egypt",
            "20",
            "EG"
        ),
        (
            64,
            "El Salvador",
            "503",
            "SV"
        ),
        (
            65,
            "Equatorial Guinea",
            "240",
            "GQ"
        ),
        (
            66,
            "Eritrea",
            "291",
            "ER"
        ),
        (
            67,
            "Estonia",
            "372",
            "EE"
        ),
        (
            68,
            "Ethiopia",
            "251",
            "ET"
        ),
        (
            69,
            "Falkland Islands",
            "500",
            "FK"
        ),
        (
            70,
            "Faroe Islands",
            "298",
            "FO"
        ),
        (
            71,
            "Fiji",
            "679",
            "FJ"
        ),
        (
            72,
            "Finland",
            "358",
            "FI"
        ),
        (
            73,
            "France",
            "33",
            "FR"
        ),
        (
            74,
            "French Polynesia",
            "689",
            "PF"
        ),
        (
            75,
            "Gabon",
            "241",
            "GA"
        ),
        (
            76,
            "Gambia",
            "220",
            "GM"
        ),
        (
            77,
            "Georgia",
            "995",
            "GE"
        ),
        (
            78,
            "Germany",
            "49",
            "DE"
        ),
        (
            79,
            "Ghana",
            "233",
            "GH"
        ),
        (
            80,
            "Gibraltar",
            "350",
            "GI"
        ),
        (
            81,
            "Greece",
            "30",
            "GR"
        ),
        (
            82,
            "Greenland",
            "299",
            "GL"
        ),
        (
            83,
            "Grenada",
            "1-473",
            "GD"
        ),
        (
            84,
            "Guam",
            "1-671",
            "GU"
        ),
        (
            85,
            "Guatemala",
            "502",
            "GT"
        ),
        (
            86,
            "Guernsey",
            "44-1481",
            "GG"
        ),
        (
            87,
            "Guinea",
            "224",
            "GN"
        ),
        (
            88,
            "Guinea-Bissau",
            "245",
            "GW"
        ),
        (
            89,
            "Guyana",
            "592",
            "GY"
        ),
        (
            90,
            "Haiti",
            "509",
            "HT"
        ),
        (
            91,
            "Honduras",
            "504",
            "HN"
        ),
        (
            92,
            "Hong Kong",
            "852",
            "HK"
        ),
        (
            93,
            "Hungary",
            "36",
            "HU"
        ),
        (
            94,
            "Iceland",
            "354",
            "IS"
        ),
        (
            95,
            "India",
            "91",
            "IN"
        ),
        (
            96,
            "Indonesia",
            "62",
            "ID"
        ),
        (
            97,
            "Iran",
            "98",
            "IR"
        ),
        (
            98,
            "Iraq",
            "964",
            "IQ"
        ),
        (
            99,
            "Ireland",
            "353",
            "IE"
        ),
        (
            100,
            "Isle of Man",
            "44-1624",
            "IM"
        ),
        (
            101,
            "Israel",
            "972",
            "IL"
        ),
        (
            102,
            "Italy",
            "39",
            "IT"
        ),
        (
            103,
            "Ivory Coast",
            "225",
            "CI"
        ),
        (
            104,
            "Jamaica",
            "1-876",
            "JM"
        ),
        (
            105,
            "Japan",
            "81",
            "JP"
        ),
        (
            106,
            "Jersey",
            "44-1534",
            "JE"
        ),
        (
            107,
            "Jordan",
            "962",
            "JO"
        ),
        (
            108,
            "Kazakhstan",
            "7",
            "KZ"
        ),
        (
            109,
            "Kenya",
            "254",
            "KE"
        ),
        (
            110,
            "Kiribati",
            "686",
            "KI"
        ),
        (
            111,
            "Kosovo",
            "383",
            "XK"
        ),
        (
            112,
            "Kuwait",
            "965",
            "KW"
        ),
        (
            113,
            "Kyrgyzstan",
            "996",
            "KG"
        ),
        (
            114,
            "Laos",
            "856",
            "LA"
        ),
        (
            115,
            "Latvia",
            "371",
            "LV"
        ),
        (
            116,
            "Lebanon",
            "961",
            "LB"
        ),
        (
            117,
            "Lesotho",
            "266",
            "LS"
        ),
        (
            118,
            "Liberia",
            "231",
            "LR"
        ),
        (
            119,
            "Libya",
            "218",
            "LY"
        ),
        (
            120,
            "Liechtenstein",
            "423",
            "LI"
        ),
        (
            121,
            "Lithuania",
            "370",
            "LT"
        ),
        (
            122,
            "Luxembourg",
            "352",
            "LU"
        ),
        (
            123,
            "Macau",
            "853",
            "MO"
        ),
        (
            124,
            "Macedonia",
            "389",
            "MK"
        ),
        (
            125,
            "Madagascar",
            "261",
            "MG"
        ),
        (
            126,
            "Malawi",
            "265",
            "MW"
        ),
        (
            127,
            "Malaysia",
            "60",
            "MY"
        ),
        (
            128,
            "Maldives",
            "960",
            "MV"
        ),
        (
            129,
            "Mali",
            "223",
            "ML"
        ),
        (
            130,
            "Malta",
            "356",
            "MT"
        ),
        (
            131,
            "Marshall Islands",
            "692",
            "MH"
        ),
        (
            132,
            "Mauritania",
            "222",
            "MR"
        ),
        (
            133,
            "Mauritius",
            "230",
            "MU"
        ),
        (
            134,
            "Mayotte",
            "262",
            "YT"
        ),
        (
            135,
            "Mexico",
            "52",
            "MX"
        ),
        (
            136,
            "Micronesia",
            "691",
            "FM"
        ),
        (
            137,
            "Moldova",
            "373",
            "MD"
        ),
        (
            138,
            "Monaco",
            "377",
            "MC"
        ),
        (
            139,
            "Mongolia",
            "976",
            "MN"
        ),
        (
            140,
            "Montenegro",
            "382",
            "ME"
        ),
        (
            141,
            "Montserrat",
            "1-664",
            "MS"
        ),
        (
            142,
            "Morocco",
            "212",
            "MA"
        ),
        (
            143,
            "Mozambique",
            "258",
            "MZ"
        ),
        (
            144,
            "Myanmar",
            "95",
            "MM"
        ),
        (
            145,
            "Namibia",
            "264",
            "NA"
        ),
        (
            146,
            "Nauru",
            "674",
            "NR"
        ),
        (
            147,
            "Nepal",
            "977",
            "NP"
        ),
        (
            148,
            "Netherlands",
            "31",
            "NL"
        ),
        (
            149,
            "Netherlands Antilles",
            "599",
            "AN"
        ),
        (
            150,
            "New Caledonia",
            "687",
            "NC"
        ),
        (
            151,
            "New Zealand",
            "64",
            "NZ"
        ),
        (
            152,
            "Nicaragua",
            "505",
            "NI"
        ),
        (
            153,
            "Niger",
            "227",
            "NE"
        ),
        (
            154,
            "Nigeria",
            "234",
            "NG"
        ),
        (
            155,
            "Niue",
            "683",
            "NU"
        ),
        (
            156,
            "North Korea",
            "850",
            "KP"
        ),
        (
            157,
            "Northern Mariana Islands",
            "1-670",
            "MP"
        ),
        (
            158,
            "Norway",
            "47",
            "NO"
        ),
        (
            159,
            "Oman",
            "968",
            "OM"
        ),
        (
            160,
            "Pakistan",
            "92",
            "PK"
        ),
        (
            161,
            "Palau",
            "680",
            "PW"
        ),
        (
            162,
            "Palestine",
            "970",
            "PS"
        ),
        (
            163,
            "Panama",
            "507",
            "PA"
        ),
        (
            164,
            "Papua New Guinea",
            "675",
            "PG"
        ),
        (
            165,
            "Paraguay",
            "595",
            "PY"
        ),
        (
            166,
            "Peru",
            "51",
            "PE"
        ),
        (
            167,
            "Philippines",
            "63",
            "PH"
        ),
        (
            168,
            "Pitcairn",
            "64",
            "PN"
        ),
        (
            169,
            "Poland",
            "48",
            "PL"
        ),
        (
            170,
            "Portugal",
            "351",
            "PT"
        ),
        (
            171,
            "Puerto Rico",
            "1-787",
            "PR"
        ),
        (
            172,
            "Qatar",
            "974",
            "QA"
        ),
        (
            173,
            "Republic of the Congo",
            "242",
            "CG"
        ),
        (
            174,
            "Reunion",
            "262",
            "RE"
        ),
        (
            175,
            "Romania",
            "40",
            "RO"
        ),
        (
            176,
            "Russia",
            "7",
            "RU"
        ),
        (
            177,
            "Rwanda",
            "250",
            "RW"
        ),
        (
            178,
            "Saint Barthelemy",
            "590",
            "BL"
        ),
        (
            179,
            "Saint Helena",
            "290",
            "SH"
        ),
        (
            180,
            "Saint Kitts and Nevis",
            "1-869",
            "KN"
        ),
        (
            181,
            "Saint Lucia",
            "1-758",
            "LC"
        ),
        (
            182,
            "Saint Martin",
            "590",
            "MF"
        ),
        (
            183,
            "Saint Pierre and Miquelon",
            "508",
            "PM"
        ),
        (
            184,
            "Saint Vincent and the Grenadines",
            "1-784",
            "VC"
        ),
        (
            185,
            "Samoa",
            "685",
            "WS"
        ),
        (
            186,
            "San Marino",
            "378",
            "SM"
        ),
        (
            187,
            "Sao Tome and Principe",
            "239",
            "ST"
        ),
        (
            188,
            "Saudi Arabia",
            "966",
            "SA"
        ),
        (
            189,
            "Senegal",
            "221",
            "SN"
        ),
        (
            190,
            "Serbia",
            "381",
            "RS"
        ),
        (
            191,
            "Seychelles",
            "248",
            "SC"
        ),
        (
            192,
            "Sierra Leone",
            "232",
            "SL"
        ),
        (
            193,
            "Singapore",
            "65",
            "SG"
        ),
        (
            194,
            "Sint Maarten",
            "1-721",
            "SX"
        ),
        (
            195,
            "Slovakia",
            "421",
            "SK"
        ),
        (
            196,
            "Slovenia",
            "386",
            "SI"
        ),
        (
            197,
            "Solomon Islands",
            "677",
            "SB"
        ),
        (
            198,
            "Somalia",
            "252",
            "SO"
        ),
        (
            199,
            "South Africa",
            "27",
            "ZA"
        ),
        (
            200,
            "South Korea",
            "82",
            "KR"
        ),
        (
            201,
            "South Sudan",
            "211",
            "SS"
        ),
        (
            202,
            "Spain",
            "34",
            "ES"
        ),
        (
            203,
            "Sri Lanka",
            "94",
            "LK"
        ),
        (
            204,
            "Sudan",
            "249",
            "SD"
        ),
        (
            205,
            "Suriname",
            "597",
            "SR"
        ),
        (
            206,
            "Svalbard and Jan Mayen",
            "47",
            "SJ"
        ),
        (
            207,
            "Swaziland",
            "268",
            "SZ"
        ),
        (
            208,
            "Sweden",
            "46",
            "SE"
        ),
        (
            209,
            "Switzerland",
            "41",
            "CH"
        ),
        (
            210,
            "Syria",
            "963",
            "SY"
        ),
        (
            211,
            "Taiwan",
            "886",
            "TW"
        ),
        (
            212,
            "Tajikistan",
            "992",
            "TJ"
        ),
        (
            213,
            "Tanzania",
            "255",
            "TZ"
        ),
        (
            214,
            "Thailand",
            "66",
            "TH"
        ),
        (
            215,
            "Togo",
            "228",
            "TG"
        ),
        (
            216,
            "Tokelau",
            "690",
            "TK"
        ),
        (
            217,
            "Tonga",
            "676",
            "TO"
        ),
        (
            218,
            "Trinidad and Tobago",
            "1-868",
            "TT"
        ),
        (
            219,
            "Tunisia",
            "216",
            "TN"
        ),
        (
            220,
            "Turkey",
            "90",
            "TR"
        ),
        (
            221,
            "Turkmenistan",
            "993",
            "TM"
        ),
        (
            222,
            "Turks and Caicos Islands",
            "1-649",
            "TC"
        ),
        (
            223,
            "Tuvalu",
            "688",
            "TV"
        ),
        (
            224,
            "U.S. Virgin Islands",
            "1-340",
            "VI"
        ),
        (
            225,
            "Uganda",
            "256",
            "UG"
        ),
        (
            226,
            "Ukraine",
            "380",
            "UA"
        ),
        (
            227,
            "United Arab Emirates",
            "971",
            "AE"
        ),
        (
            228,
            "United Kingdom",
            "44",
            "GB"
        ),
        (
            229,
            "United States",
            "1",
            "US"
        ),
        (
            230,
            "Uruguay",
            "598",
            "UY"
        ),
        (
            231,
            "Uzbekistan",
            "998",
            "UZ"
        ),
        (
            232,
            "Vanuatu",
            "678",
            "VU"
        ),
        (
            233,
            "Vatican",
            "379",
            "VA"
        ),
        (
            234,
            "Venezuela",
            "58",
            "VE"
        ),
        (
            235,
            "Vietnam",
            "84",
            "VN"
        ),
        (
            236,
            "Wallis and Futuna",
            "681",
            "WF"
        ),
        (
            237,
            "Western Sahara",
            "212",
            "EH"
        ),
        (
            238,
            "Yemen",
            "967",
            "YE"
        ),
        (
            239,
            "Zambia",
            "260",
            "ZM"
        ),
        (
            240,
            "Zimbabwe",
            "263",
            "ZW"
        )
;